ignore:
  - "/home/runner/work/CryptoLib/CryptoLib/util/src_util/process_security.c"
  - "/home/runner/work/CryptoLib/CryptoLib/util/src_util/ut_mysql_tls_connection.c"
  - "/home/runner/work/CryptoLib/CryptoLib/util/src_util/ut_mysql_m_tls_connection.c"
  - "/home/runner/work/CryptoLib/CryptoLib/util/src_util/apply_security.c"
  - "/home/runner/work/CryptoLib/CryptoLib/util/src_util/crypto_sequence.c"
  - "/home/runner/work/CryptoLib/CryptoLib/src/src_main/crypto_print.c"
  - "/home/runner/work/CryptoLib/CryptoLib/util/include/utest.h"
  - "/home/runner/work/CryptoLib/CryptoLib/util/core/shared_util.c"
  - "/home/runner/work/CryptoLib/CryptoLib/src/src_feature_stubs/cryptography_kmc_stub/cryptography_interface_kmc.stub.c"
  - "/home/runner/work/CryptoLib/CryptoLib/src/src_feature_stubs/mysql_stub/sadb_routine_mariadb.stub.c"
  
