ignore:
  - "src/crypto/kmc/*"
  - "src/crypto/kmc_stub/*"
  - "src/crypto/libgcrypt_stub/*"
  - "src/sa/internal_stub/*"
  - "src/sa/mariadb/*"
  - "src/sa/mariadb_stub/*"
  - "src/sa/sadb_mariadb_sql/*"
  - "src/sa/test_sadb_mariadb_sql/*"
  - "support/*"
  - "test/*"